### ISSUE TITLE
README not precise

### ISSUE THREAD

**Issue by MeisterJustice** [Coderdivine/Lazerpay-python-sdk#1]
First thing a dev does when they come in a repo for an SDK is to checkout the docs (README). Could we update the file to contain a detailed README? From how to install the SDK, to how to use it.

We can use this for reference [https://github.com/LazerPay-Finance/lazerpay-react-native](https://github.com/LazerPay-Finance/lazerpay-react-native) and [https://github.com/LazerPay-Finance/lazerpay-node-sdk](https://github.com/LazerPay-Finance/lazerpay-node-sdk)

**Comment by Coderdivine** [comment]
Updated REABME.md
